import "@/app/globals.css";

import Footer from "@/components/Footer";
import Loading from "./loading";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "PM Next-app",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
        <Navbar/>
        <Suspense fallback={<Loading/>}>
        {children}
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
